[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
shade = "3ucYdoYVtvq5dNHqCYWL1WR8kgN4dgDrKnxRK7SN65oN"

[programs.devnet]
shade = "DTW1EWDEsqTi4XvWSRkad138eHQcQxVs7mV9YXivcaox"

[programs.mainnet]
shade = "3ucYdoYVtvq5dNHqCYWL1WR8kgN4dgDrKnxRK7SN65oN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "D:/Dev/Keys/shade-deployer.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/new-threshold-test.ts"
