[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
shade = "DBHZSH4Zg3DB2sL8FHnamXAVcCg2N1Q3ow8qYYkmgzqv"

[programs.devnet]
shade = "DBHZSH4Zg3DB2sL8FHnamXAVcCg2N1Q3ow8qYYkmgzqv"

[programs.mainnet]
shade = "DBHZSH4Zg3DB2sL8FHnamXAVcCg2N1Q3ow8qYYkmgzqv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
