[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
shade = "XEyyUoXxLN3DE9ezqwUvPp8FZehunWxmkcsWyoi8vzG"

[programs.devnet]
shade = "XEyyUoXxLN3DE9ezqwUvPp8FZehunWxmkcsWyoi8vzG"

[programs.mainnet]
shade = "XEyyUoXxLN3DE9ezqwUvPp8FZehunWxmkcsWyoi8vzG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "D:/Dev/Keys/shade-deployer.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
